package com.qi.menu.web.model.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BasicSystemExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public BasicSystemExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected BasicSystemExample(BasicSystemExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_basic_system_registry
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return this;
        }

        public Criteria andGuidEqualTo(Long value) {
            addCriterion("Guid =", value, "guid");
            return this;
        }

        public Criteria andGuidNotEqualTo(Long value) {
            addCriterion("Guid <>", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThan(Long value) {
            addCriterion("Guid >", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(Long value) {
            addCriterion("Guid >=", value, "guid");
            return this;
        }

        public Criteria andGuidLessThan(Long value) {
            addCriterion("Guid <", value, "guid");
            return this;
        }

        public Criteria andGuidLessThanOrEqualTo(Long value) {
            addCriterion("Guid <=", value, "guid");
            return this;
        }

        public Criteria andGuidIn(List values) {
            addCriterion("Guid in", values, "guid");
            return this;
        }

        public Criteria andGuidNotIn(List values) {
            addCriterion("Guid not in", values, "guid");
            return this;
        }

        public Criteria andGuidBetween(Long value1, Long value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return this;
        }

        public Criteria andGuidNotBetween(Long value1, Long value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("Code is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("Code is not null");
            return this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("Code =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("Code <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("Code >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Code >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("Code <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("Code <=", value, "code");
            return this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("Code like", value, "code");
            return this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("Code not like", value, "code");
            return this;
        }

        public Criteria andCodeIn(List values) {
            addCriterion("Code in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List values) {
            addCriterion("Code not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("Code between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("Code not between", value1, value2, "code");
            return this;
        }

        public Criteria andNamecnIsNull() {
            addCriterion("NameCn is null");
            return this;
        }

        public Criteria andNamecnIsNotNull() {
            addCriterion("NameCn is not null");
            return this;
        }

        public Criteria andNamecnEqualTo(String value) {
            addCriterion("NameCn =", value, "namecn");
            return this;
        }

        public Criteria andNamecnNotEqualTo(String value) {
            addCriterion("NameCn <>", value, "namecn");
            return this;
        }

        public Criteria andNamecnGreaterThan(String value) {
            addCriterion("NameCn >", value, "namecn");
            return this;
        }

        public Criteria andNamecnGreaterThanOrEqualTo(String value) {
            addCriterion("NameCn >=", value, "namecn");
            return this;
        }

        public Criteria andNamecnLessThan(String value) {
            addCriterion("NameCn <", value, "namecn");
            return this;
        }

        public Criteria andNamecnLessThanOrEqualTo(String value) {
            addCriterion("NameCn <=", value, "namecn");
            return this;
        }

        public Criteria andNamecnLike(String value) {
            addCriterion("NameCn like", value, "namecn");
            return this;
        }

        public Criteria andNamecnNotLike(String value) {
            addCriterion("NameCn not like", value, "namecn");
            return this;
        }

        public Criteria andNamecnIn(List values) {
            addCriterion("NameCn in", values, "namecn");
            return this;
        }

        public Criteria andNamecnNotIn(List values) {
            addCriterion("NameCn not in", values, "namecn");
            return this;
        }

        public Criteria andNamecnBetween(String value1, String value2) {
            addCriterion("NameCn between", value1, value2, "namecn");
            return this;
        }

        public Criteria andNamecnNotBetween(String value1, String value2) {
            addCriterion("NameCn not between", value1, value2, "namecn");
            return this;
        }

        public Criteria andNameenIsNull() {
            addCriterion("NameEn is null");
            return this;
        }

        public Criteria andNameenIsNotNull() {
            addCriterion("NameEn is not null");
            return this;
        }

        public Criteria andNameenEqualTo(String value) {
            addCriterion("NameEn =", value, "nameen");
            return this;
        }

        public Criteria andNameenNotEqualTo(String value) {
            addCriterion("NameEn <>", value, "nameen");
            return this;
        }

        public Criteria andNameenGreaterThan(String value) {
            addCriterion("NameEn >", value, "nameen");
            return this;
        }

        public Criteria andNameenGreaterThanOrEqualTo(String value) {
            addCriterion("NameEn >=", value, "nameen");
            return this;
        }

        public Criteria andNameenLessThan(String value) {
            addCriterion("NameEn <", value, "nameen");
            return this;
        }

        public Criteria andNameenLessThanOrEqualTo(String value) {
            addCriterion("NameEn <=", value, "nameen");
            return this;
        }

        public Criteria andNameenLike(String value) {
            addCriterion("NameEn like", value, "nameen");
            return this;
        }

        public Criteria andNameenNotLike(String value) {
            addCriterion("NameEn not like", value, "nameen");
            return this;
        }

        public Criteria andNameenIn(List values) {
            addCriterion("NameEn in", values, "nameen");
            return this;
        }

        public Criteria andNameenNotIn(List values) {
            addCriterion("NameEn not in", values, "nameen");
            return this;
        }

        public Criteria andNameenBetween(String value1, String value2) {
            addCriterion("NameEn between", value1, value2, "nameen");
            return this;
        }

        public Criteria andNameenNotBetween(String value1, String value2) {
            addCriterion("NameEn not between", value1, value2, "nameen");
            return this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("Domain is null");
            return this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("Domain is not null");
            return this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("Domain =", value, "domain");
            return this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("Domain <>", value, "domain");
            return this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("Domain >", value, "domain");
            return this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("Domain >=", value, "domain");
            return this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("Domain <", value, "domain");
            return this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("Domain <=", value, "domain");
            return this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("Domain like", value, "domain");
            return this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("Domain not like", value, "domain");
            return this;
        }

        public Criteria andDomainIn(List values) {
            addCriterion("Domain in", values, "domain");
            return this;
        }

        public Criteria andDomainNotIn(List values) {
            addCriterion("Domain not in", values, "domain");
            return this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("Domain between", value1, value2, "domain");
            return this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("Domain not between", value1, value2, "domain");
            return this;
        }

        public Criteria andContextpathIsNull() {
            addCriterion("ContextPath is null");
            return this;
        }

        public Criteria andContextpathIsNotNull() {
            addCriterion("ContextPath is not null");
            return this;
        }

        public Criteria andContextpathEqualTo(String value) {
            addCriterion("ContextPath =", value, "contextpath");
            return this;
        }

        public Criteria andContextpathNotEqualTo(String value) {
            addCriterion("ContextPath <>", value, "contextpath");
            return this;
        }

        public Criteria andContextpathGreaterThan(String value) {
            addCriterion("ContextPath >", value, "contextpath");
            return this;
        }

        public Criteria andContextpathGreaterThanOrEqualTo(String value) {
            addCriterion("ContextPath >=", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLessThan(String value) {
            addCriterion("ContextPath <", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLessThanOrEqualTo(String value) {
            addCriterion("ContextPath <=", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLike(String value) {
            addCriterion("ContextPath like", value, "contextpath");
            return this;
        }

        public Criteria andContextpathNotLike(String value) {
            addCriterion("ContextPath not like", value, "contextpath");
            return this;
        }

        public Criteria andContextpathIn(List values) {
            addCriterion("ContextPath in", values, "contextpath");
            return this;
        }

        public Criteria andContextpathNotIn(List values) {
            addCriterion("ContextPath not in", values, "contextpath");
            return this;
        }

        public Criteria andContextpathBetween(String value1, String value2) {
            addCriterion("ContextPath between", value1, value2, "contextpath");
            return this;
        }

        public Criteria andContextpathNotBetween(String value1, String value2) {
            addCriterion("ContextPath not between", value1, value2, "contextpath");
            return this;
        }

        public Criteria andHomepageIsNull() {
            addCriterion("HomePage is null");
            return this;
        }

        public Criteria andHomepageIsNotNull() {
            addCriterion("HomePage is not null");
            return this;
        }

        public Criteria andHomepageEqualTo(String value) {
            addCriterion("HomePage =", value, "homepage");
            return this;
        }

        public Criteria andHomepageNotEqualTo(String value) {
            addCriterion("HomePage <>", value, "homepage");
            return this;
        }

        public Criteria andHomepageGreaterThan(String value) {
            addCriterion("HomePage >", value, "homepage");
            return this;
        }

        public Criteria andHomepageGreaterThanOrEqualTo(String value) {
            addCriterion("HomePage >=", value, "homepage");
            return this;
        }

        public Criteria andHomepageLessThan(String value) {
            addCriterion("HomePage <", value, "homepage");
            return this;
        }

        public Criteria andHomepageLessThanOrEqualTo(String value) {
            addCriterion("HomePage <=", value, "homepage");
            return this;
        }

        public Criteria andHomepageLike(String value) {
            addCriterion("HomePage like", value, "homepage");
            return this;
        }

        public Criteria andHomepageNotLike(String value) {
            addCriterion("HomePage not like", value, "homepage");
            return this;
        }

        public Criteria andHomepageIn(List values) {
            addCriterion("HomePage in", values, "homepage");
            return this;
        }

        public Criteria andHomepageNotIn(List values) {
            addCriterion("HomePage not in", values, "homepage");
            return this;
        }

        public Criteria andHomepageBetween(String value1, String value2) {
            addCriterion("HomePage between", value1, value2, "homepage");
            return this;
        }

        public Criteria andHomepageNotBetween(String value1, String value2) {
            addCriterion("HomePage not between", value1, value2, "homepage");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("Type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("Type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("Type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("Type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("Type <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("Type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("Type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("Type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("Type not between", value1, value2, "type");
            return this;
        }

        public Criteria andLogopathIsNull() {
            addCriterion("LogoPath is null");
            return this;
        }

        public Criteria andLogopathIsNotNull() {
            addCriterion("LogoPath is not null");
            return this;
        }

        public Criteria andLogopathEqualTo(String value) {
            addCriterion("LogoPath =", value, "logopath");
            return this;
        }

        public Criteria andLogopathNotEqualTo(String value) {
            addCriterion("LogoPath <>", value, "logopath");
            return this;
        }

        public Criteria andLogopathGreaterThan(String value) {
            addCriterion("LogoPath >", value, "logopath");
            return this;
        }

        public Criteria andLogopathGreaterThanOrEqualTo(String value) {
            addCriterion("LogoPath >=", value, "logopath");
            return this;
        }

        public Criteria andLogopathLessThan(String value) {
            addCriterion("LogoPath <", value, "logopath");
            return this;
        }

        public Criteria andLogopathLessThanOrEqualTo(String value) {
            addCriterion("LogoPath <=", value, "logopath");
            return this;
        }

        public Criteria andLogopathLike(String value) {
            addCriterion("LogoPath like", value, "logopath");
            return this;
        }

        public Criteria andLogopathNotLike(String value) {
            addCriterion("LogoPath not like", value, "logopath");
            return this;
        }

        public Criteria andLogopathIn(List values) {
            addCriterion("LogoPath in", values, "logopath");
            return this;
        }

        public Criteria andLogopathNotIn(List values) {
            addCriterion("LogoPath not in", values, "logopath");
            return this;
        }

        public Criteria andLogopathBetween(String value1, String value2) {
            addCriterion("LogoPath between", value1, value2, "logopath");
            return this;
        }

        public Criteria andLogopathNotBetween(String value1, String value2) {
            addCriterion("LogoPath not between", value1, value2, "logopath");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("Status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("Status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("Status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("Status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("Status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("Status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("Status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Status not between", value1, value2, "status");
            return this;
        }
    }
}