package com.qi.menu.web.model.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BasicMenuExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public BasicMenuExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected BasicMenuExample(BasicMenuExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_basic_menu
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return this;
        }

        public Criteria andGuidEqualTo(Long value) {
            addCriterion("Guid =", value, "guid");
            return this;
        }

        public Criteria andGuidNotEqualTo(Long value) {
            addCriterion("Guid <>", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThan(Long value) {
            addCriterion("Guid >", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(Long value) {
            addCriterion("Guid >=", value, "guid");
            return this;
        }

        public Criteria andGuidLessThan(Long value) {
            addCriterion("Guid <", value, "guid");
            return this;
        }

        public Criteria andGuidLessThanOrEqualTo(Long value) {
            addCriterion("Guid <=", value, "guid");
            return this;
        }

        public Criteria andGuidIn(List values) {
            addCriterion("Guid in", values, "guid");
            return this;
        }

        public Criteria andGuidNotIn(List values) {
            addCriterion("Guid not in", values, "guid");
            return this;
        }

        public Criteria andGuidBetween(Long value1, Long value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return this;
        }

        public Criteria andGuidNotBetween(Long value1, Long value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("ParentID is null");
            return this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("ParentID is not null");
            return this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("ParentID =", value, "parentid");
            return this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("ParentID <>", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("ParentID >", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("ParentID >=", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("ParentID <", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("ParentID <=", value, "parentid");
            return this;
        }

        public Criteria andParentidIn(List values) {
            addCriterion("ParentID in", values, "parentid");
            return this;
        }

        public Criteria andParentidNotIn(List values) {
            addCriterion("ParentID not in", values, "parentid");
            return this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("ParentID between", value1, value2, "parentid");
            return this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("ParentID not between", value1, value2, "parentid");
            return this;
        }

        public Criteria andParentnameIsNull() {
            addCriterion("ParentName is null");
            return this;
        }

        public Criteria andParentnameIsNotNull() {
            addCriterion("ParentName is not null");
            return this;
        }

        public Criteria andParentnameEqualTo(String value) {
            addCriterion("ParentName =", value, "parentname");
            return this;
        }

        public Criteria andParentnameNotEqualTo(String value) {
            addCriterion("ParentName <>", value, "parentname");
            return this;
        }

        public Criteria andParentnameGreaterThan(String value) {
            addCriterion("ParentName >", value, "parentname");
            return this;
        }

        public Criteria andParentnameGreaterThanOrEqualTo(String value) {
            addCriterion("ParentName >=", value, "parentname");
            return this;
        }

        public Criteria andParentnameLessThan(String value) {
            addCriterion("ParentName <", value, "parentname");
            return this;
        }

        public Criteria andParentnameLessThanOrEqualTo(String value) {
            addCriterion("ParentName <=", value, "parentname");
            return this;
        }

        public Criteria andParentnameLike(String value) {
            addCriterion("ParentName like", value, "parentname");
            return this;
        }

        public Criteria andParentnameNotLike(String value) {
            addCriterion("ParentName not like", value, "parentname");
            return this;
        }

        public Criteria andParentnameIn(List values) {
            addCriterion("ParentName in", values, "parentname");
            return this;
        }

        public Criteria andParentnameNotIn(List values) {
            addCriterion("ParentName not in", values, "parentname");
            return this;
        }

        public Criteria andParentnameBetween(String value1, String value2) {
            addCriterion("ParentName between", value1, value2, "parentname");
            return this;
        }

        public Criteria andParentnameNotBetween(String value1, String value2) {
            addCriterion("ParentName not between", value1, value2, "parentname");
            return this;
        }

        public Criteria andSystemcodeIsNull() {
            addCriterion("SystemCode is null");
            return this;
        }

        public Criteria andSystemcodeIsNotNull() {
            addCriterion("SystemCode is not null");
            return this;
        }

        public Criteria andSystemcodeEqualTo(String value) {
            addCriterion("SystemCode =", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeNotEqualTo(String value) {
            addCriterion("SystemCode <>", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeGreaterThan(String value) {
            addCriterion("SystemCode >", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeGreaterThanOrEqualTo(String value) {
            addCriterion("SystemCode >=", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeLessThan(String value) {
            addCriterion("SystemCode <", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeLessThanOrEqualTo(String value) {
            addCriterion("SystemCode <=", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeLike(String value) {
            addCriterion("SystemCode like", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeNotLike(String value) {
            addCriterion("SystemCode not like", value, "systemcode");
            return this;
        }

        public Criteria andSystemcodeIn(List values) {
            addCriterion("SystemCode in", values, "systemcode");
            return this;
        }

        public Criteria andSystemcodeNotIn(List values) {
            addCriterion("SystemCode not in", values, "systemcode");
            return this;
        }

        public Criteria andSystemcodeBetween(String value1, String value2) {
            addCriterion("SystemCode between", value1, value2, "systemcode");
            return this;
        }

        public Criteria andSystemcodeNotBetween(String value1, String value2) {
            addCriterion("SystemCode not between", value1, value2, "systemcode");
            return this;
        }

        public Criteria andMenucodeIsNull() {
            addCriterion("MenuCode is null");
            return this;
        }

        public Criteria andMenucodeIsNotNull() {
            addCriterion("MenuCode is not null");
            return this;
        }

        public Criteria andMenucodeEqualTo(String value) {
            addCriterion("MenuCode =", value, "menucode");
            return this;
        }

        public Criteria andMenucodeNotEqualTo(String value) {
            addCriterion("MenuCode <>", value, "menucode");
            return this;
        }

        public Criteria andMenucodeGreaterThan(String value) {
            addCriterion("MenuCode >", value, "menucode");
            return this;
        }

        public Criteria andMenucodeGreaterThanOrEqualTo(String value) {
            addCriterion("MenuCode >=", value, "menucode");
            return this;
        }

        public Criteria andMenucodeLessThan(String value) {
            addCriterion("MenuCode <", value, "menucode");
            return this;
        }

        public Criteria andMenucodeLessThanOrEqualTo(String value) {
            addCriterion("MenuCode <=", value, "menucode");
            return this;
        }

        public Criteria andMenucodeLike(String value) {
            addCriterion("MenuCode like", value, "menucode");
            return this;
        }

        public Criteria andMenucodeNotLike(String value) {
            addCriterion("MenuCode not like", value, "menucode");
            return this;
        }

        public Criteria andMenucodeIn(List values) {
            addCriterion("MenuCode in", values, "menucode");
            return this;
        }

        public Criteria andMenucodeNotIn(List values) {
            addCriterion("MenuCode not in", values, "menucode");
            return this;
        }

        public Criteria andMenucodeBetween(String value1, String value2) {
            addCriterion("MenuCode between", value1, value2, "menucode");
            return this;
        }

        public Criteria andMenucodeNotBetween(String value1, String value2) {
            addCriterion("MenuCode not between", value1, value2, "menucode");
            return this;
        }

        public Criteria andMenunameIsNull() {
            addCriterion("MenuName is null");
            return this;
        }

        public Criteria andMenunameIsNotNull() {
            addCriterion("MenuName is not null");
            return this;
        }

        public Criteria andMenunameEqualTo(String value) {
            addCriterion("MenuName =", value, "menuname");
            return this;
        }

        public Criteria andMenunameNotEqualTo(String value) {
            addCriterion("MenuName <>", value, "menuname");
            return this;
        }

        public Criteria andMenunameGreaterThan(String value) {
            addCriterion("MenuName >", value, "menuname");
            return this;
        }

        public Criteria andMenunameGreaterThanOrEqualTo(String value) {
            addCriterion("MenuName >=", value, "menuname");
            return this;
        }

        public Criteria andMenunameLessThan(String value) {
            addCriterion("MenuName <", value, "menuname");
            return this;
        }

        public Criteria andMenunameLessThanOrEqualTo(String value) {
            addCriterion("MenuName <=", value, "menuname");
            return this;
        }

        public Criteria andMenunameLike(String value) {
            addCriterion("MenuName like", value, "menuname");
            return this;
        }

        public Criteria andMenunameNotLike(String value) {
            addCriterion("MenuName not like", value, "menuname");
            return this;
        }

        public Criteria andMenunameIn(List values) {
            addCriterion("MenuName in", values, "menuname");
            return this;
        }

        public Criteria andMenunameNotIn(List values) {
            addCriterion("MenuName not in", values, "menuname");
            return this;
        }

        public Criteria andMenunameBetween(String value1, String value2) {
            addCriterion("MenuName between", value1, value2, "menuname");
            return this;
        }

        public Criteria andMenunameNotBetween(String value1, String value2) {
            addCriterion("MenuName not between", value1, value2, "menuname");
            return this;
        }

        public Criteria andContextpathIsNull() {
            addCriterion("ContextPath is null");
            return this;
        }

        public Criteria andContextpathIsNotNull() {
            addCriterion("ContextPath is not null");
            return this;
        }

        public Criteria andContextpathEqualTo(String value) {
            addCriterion("ContextPath =", value, "contextpath");
            return this;
        }

        public Criteria andContextpathNotEqualTo(String value) {
            addCriterion("ContextPath <>", value, "contextpath");
            return this;
        }

        public Criteria andContextpathGreaterThan(String value) {
            addCriterion("ContextPath >", value, "contextpath");
            return this;
        }

        public Criteria andContextpathGreaterThanOrEqualTo(String value) {
            addCriterion("ContextPath >=", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLessThan(String value) {
            addCriterion("ContextPath <", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLessThanOrEqualTo(String value) {
            addCriterion("ContextPath <=", value, "contextpath");
            return this;
        }

        public Criteria andContextpathLike(String value) {
            addCriterion("ContextPath like", value, "contextpath");
            return this;
        }

        public Criteria andContextpathNotLike(String value) {
            addCriterion("ContextPath not like", value, "contextpath");
            return this;
        }

        public Criteria andContextpathIn(List values) {
            addCriterion("ContextPath in", values, "contextpath");
            return this;
        }

        public Criteria andContextpathNotIn(List values) {
            addCriterion("ContextPath not in", values, "contextpath");
            return this;
        }

        public Criteria andContextpathBetween(String value1, String value2) {
            addCriterion("ContextPath between", value1, value2, "contextpath");
            return this;
        }

        public Criteria andContextpathNotBetween(String value1, String value2) {
            addCriterion("ContextPath not between", value1, value2, "contextpath");
            return this;
        }

        public Criteria andControllerIsNull() {
            addCriterion("Controller is null");
            return this;
        }

        public Criteria andControllerIsNotNull() {
            addCriterion("Controller is not null");
            return this;
        }

        public Criteria andControllerEqualTo(String value) {
            addCriterion("Controller =", value, "controller");
            return this;
        }

        public Criteria andControllerNotEqualTo(String value) {
            addCriterion("Controller <>", value, "controller");
            return this;
        }

        public Criteria andControllerGreaterThan(String value) {
            addCriterion("Controller >", value, "controller");
            return this;
        }

        public Criteria andControllerGreaterThanOrEqualTo(String value) {
            addCriterion("Controller >=", value, "controller");
            return this;
        }

        public Criteria andControllerLessThan(String value) {
            addCriterion("Controller <", value, "controller");
            return this;
        }

        public Criteria andControllerLessThanOrEqualTo(String value) {
            addCriterion("Controller <=", value, "controller");
            return this;
        }

        public Criteria andControllerLike(String value) {
            addCriterion("Controller like", value, "controller");
            return this;
        }

        public Criteria andControllerNotLike(String value) {
            addCriterion("Controller not like", value, "controller");
            return this;
        }

        public Criteria andControllerIn(List values) {
            addCriterion("Controller in", values, "controller");
            return this;
        }

        public Criteria andControllerNotIn(List values) {
            addCriterion("Controller not in", values, "controller");
            return this;
        }

        public Criteria andControllerBetween(String value1, String value2) {
            addCriterion("Controller between", value1, value2, "controller");
            return this;
        }

        public Criteria andControllerNotBetween(String value1, String value2) {
            addCriterion("Controller not between", value1, value2, "controller");
            return this;
        }

        public Criteria andRequestmappingIsNull() {
            addCriterion("RequestMapping is null");
            return this;
        }

        public Criteria andRequestmappingIsNotNull() {
            addCriterion("RequestMapping is not null");
            return this;
        }

        public Criteria andRequestmappingEqualTo(String value) {
            addCriterion("RequestMapping =", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingNotEqualTo(String value) {
            addCriterion("RequestMapping <>", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingGreaterThan(String value) {
            addCriterion("RequestMapping >", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingGreaterThanOrEqualTo(String value) {
            addCriterion("RequestMapping >=", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingLessThan(String value) {
            addCriterion("RequestMapping <", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingLessThanOrEqualTo(String value) {
            addCriterion("RequestMapping <=", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingLike(String value) {
            addCriterion("RequestMapping like", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingNotLike(String value) {
            addCriterion("RequestMapping not like", value, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingIn(List values) {
            addCriterion("RequestMapping in", values, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingNotIn(List values) {
            addCriterion("RequestMapping not in", values, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingBetween(String value1, String value2) {
            addCriterion("RequestMapping between", value1, value2, "requestmapping");
            return this;
        }

        public Criteria andRequestmappingNotBetween(String value1, String value2) {
            addCriterion("RequestMapping not between", value1, value2, "requestmapping");
            return this;
        }

        public Criteria andIconpathIsNull() {
            addCriterion("IconPath is null");
            return this;
        }

        public Criteria andIconpathIsNotNull() {
            addCriterion("IconPath is not null");
            return this;
        }

        public Criteria andIconpathEqualTo(String value) {
            addCriterion("IconPath =", value, "iconpath");
            return this;
        }

        public Criteria andIconpathNotEqualTo(String value) {
            addCriterion("IconPath <>", value, "iconpath");
            return this;
        }

        public Criteria andIconpathGreaterThan(String value) {
            addCriterion("IconPath >", value, "iconpath");
            return this;
        }

        public Criteria andIconpathGreaterThanOrEqualTo(String value) {
            addCriterion("IconPath >=", value, "iconpath");
            return this;
        }

        public Criteria andIconpathLessThan(String value) {
            addCriterion("IconPath <", value, "iconpath");
            return this;
        }

        public Criteria andIconpathLessThanOrEqualTo(String value) {
            addCriterion("IconPath <=", value, "iconpath");
            return this;
        }

        public Criteria andIconpathLike(String value) {
            addCriterion("IconPath like", value, "iconpath");
            return this;
        }

        public Criteria andIconpathNotLike(String value) {
            addCriterion("IconPath not like", value, "iconpath");
            return this;
        }

        public Criteria andIconpathIn(List values) {
            addCriterion("IconPath in", values, "iconpath");
            return this;
        }

        public Criteria andIconpathNotIn(List values) {
            addCriterion("IconPath not in", values, "iconpath");
            return this;
        }

        public Criteria andIconpathBetween(String value1, String value2) {
            addCriterion("IconPath between", value1, value2, "iconpath");
            return this;
        }

        public Criteria andIconpathNotBetween(String value1, String value2) {
            addCriterion("IconPath not between", value1, value2, "iconpath");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("Description in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("Description not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return this;
        }

        public Criteria andRootidIsNull() {
            addCriterion("RootID is null");
            return this;
        }

        public Criteria andRootidIsNotNull() {
            addCriterion("RootID is not null");
            return this;
        }

        public Criteria andRootidEqualTo(Long value) {
            addCriterion("RootID =", value, "rootid");
            return this;
        }

        public Criteria andRootidNotEqualTo(Long value) {
            addCriterion("RootID <>", value, "rootid");
            return this;
        }

        public Criteria andRootidGreaterThan(Long value) {
            addCriterion("RootID >", value, "rootid");
            return this;
        }

        public Criteria andRootidGreaterThanOrEqualTo(Long value) {
            addCriterion("RootID >=", value, "rootid");
            return this;
        }

        public Criteria andRootidLessThan(Long value) {
            addCriterion("RootID <", value, "rootid");
            return this;
        }

        public Criteria andRootidLessThanOrEqualTo(Long value) {
            addCriterion("RootID <=", value, "rootid");
            return this;
        }

        public Criteria andRootidIn(List values) {
            addCriterion("RootID in", values, "rootid");
            return this;
        }

        public Criteria andRootidNotIn(List values) {
            addCriterion("RootID not in", values, "rootid");
            return this;
        }

        public Criteria andRootidBetween(Long value1, Long value2) {
            addCriterion("RootID between", value1, value2, "rootid");
            return this;
        }

        public Criteria andRootidNotBetween(Long value1, Long value2) {
            addCriterion("RootID not between", value1, value2, "rootid");
            return this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("Level is null");
            return this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("Level is not null");
            return this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("Level =", value, "level");
            return this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("Level <>", value, "level");
            return this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("Level >", value, "level");
            return this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("Level >=", value, "level");
            return this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("Level <", value, "level");
            return this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("Level <=", value, "level");
            return this;
        }

        public Criteria andLevelIn(List values) {
            addCriterion("Level in", values, "level");
            return this;
        }

        public Criteria andLevelNotIn(List values) {
            addCriterion("Level not in", values, "level");
            return this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("Level between", value1, value2, "level");
            return this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("Level not between", value1, value2, "level");
            return this;
        }

        public Criteria andSortIsNull() {
            addCriterion("Sort is null");
            return this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("Sort is not null");
            return this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("Sort =", value, "sort");
            return this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("Sort <>", value, "sort");
            return this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("Sort >", value, "sort");
            return this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sort >=", value, "sort");
            return this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("Sort <", value, "sort");
            return this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("Sort <=", value, "sort");
            return this;
        }

        public Criteria andSortIn(List values) {
            addCriterion("Sort in", values, "sort");
            return this;
        }

        public Criteria andSortNotIn(List values) {
            addCriterion("Sort not in", values, "sort");
            return this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("Sort between", value1, value2, "sort");
            return this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("Sort not between", value1, value2, "sort");
            return this;
        }

        public Criteria andIsleafIsNull() {
            addCriterion("IsLeaf is null");
            return this;
        }

        public Criteria andIsleafIsNotNull() {
            addCriterion("IsLeaf is not null");
            return this;
        }

        public Criteria andIsleafEqualTo(Boolean value) {
            addCriterion("IsLeaf =", value, "isleaf");
            return this;
        }

        public Criteria andIsleafNotEqualTo(Boolean value) {
            addCriterion("IsLeaf <>", value, "isleaf");
            return this;
        }

        public Criteria andIsleafGreaterThan(Boolean value) {
            addCriterion("IsLeaf >", value, "isleaf");
            return this;
        }

        public Criteria andIsleafGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsLeaf >=", value, "isleaf");
            return this;
        }

        public Criteria andIsleafLessThan(Boolean value) {
            addCriterion("IsLeaf <", value, "isleaf");
            return this;
        }

        public Criteria andIsleafLessThanOrEqualTo(Boolean value) {
            addCriterion("IsLeaf <=", value, "isleaf");
            return this;
        }

        public Criteria andIsleafIn(List values) {
            addCriterion("IsLeaf in", values, "isleaf");
            return this;
        }

        public Criteria andIsleafNotIn(List values) {
            addCriterion("IsLeaf not in", values, "isleaf");
            return this;
        }

        public Criteria andIsleafBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLeaf between", value1, value2, "isleaf");
            return this;
        }

        public Criteria andIsleafNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLeaf not between", value1, value2, "isleaf");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("Status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("Status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("Status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("Status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("Status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("Status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("Status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("Status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Status not between", value1, value2, "status");
            return this;
        }
    }
}