package com.qi.dict.web.model.model;

import com.qi.common.dao.model.BaseModel;

public class Dictionary extends BaseModel{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.Guid
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.ParentCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private String parentcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.DictCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private String dictcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.DictName
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private String dictname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.Description
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.Sort
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private Integer sort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_dictionary.Status
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    private Boolean status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.Guid
     *
     * @return the value of t_basic_dictionary.Guid
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.Guid
     *
     * @param guid the value for t_basic_dictionary.Guid
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.ParentCode
     *
     * @return the value of t_basic_dictionary.ParentCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.ParentCode
     *
     * @param parentcode the value for t_basic_dictionary.ParentCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.DictCode
     *
     * @return the value of t_basic_dictionary.DictCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public String getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.DictCode
     *
     * @param dictcode the value for t_basic_dictionary.DictCode
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setDictcode(String dictcode) {
        this.dictcode = dictcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.DictName
     *
     * @return the value of t_basic_dictionary.DictName
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public String getDictname() {
        return dictname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.DictName
     *
     * @param dictname the value for t_basic_dictionary.DictName
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setDictname(String dictname) {
        this.dictname = dictname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.Description
     *
     * @return the value of t_basic_dictionary.Description
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.Description
     *
     * @param description the value for t_basic_dictionary.Description
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.Sort
     *
     * @return the value of t_basic_dictionary.Sort
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.Sort
     *
     * @param sort the value for t_basic_dictionary.Sort
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_dictionary.Status
     *
     * @return the value of t_basic_dictionary.Status
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_dictionary.Status
     *
     * @param status the value for t_basic_dictionary.Status
     *
     * @ibatorgenerated Mon Jul 25 15:45:32 GMT+08:00 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}