# Server Settings (ServerProperties)
server:
  port: 8888
  contextPath: /project
  tomcat:
    uri-encoding: utf-8
# Spring Settings
spring:
# profiles Settings
  profiles:
    active: dev
# Thymeleaf Settings
  thymeleaf:
    cache: false
    suffix: .html