package com.qi.menu.model.domain;

import com.qi.common.dao.model.BaseModel;

public class BasicSystem extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.Guid
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.Code
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.NameCn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String namecn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.NameEn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String nameen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.Domain
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String domain;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.ContextPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String contextpath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.HomePage
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String homepage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.Type
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.LogoPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private String logopath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_basic_system_registry.Status
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    private Integer status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.Guid
     *
     * @return the value of t_basic_system_registry.Guid
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.Guid
     *
     * @param guid the value for t_basic_system_registry.Guid
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.Code
     *
     * @return the value of t_basic_system_registry.Code
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.Code
     *
     * @param code the value for t_basic_system_registry.Code
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.NameCn
     *
     * @return the value of t_basic_system_registry.NameCn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getNamecn() {
        return namecn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.NameCn
     *
     * @param namecn the value for t_basic_system_registry.NameCn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setNamecn(String namecn) {
        this.namecn = namecn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.NameEn
     *
     * @return the value of t_basic_system_registry.NameEn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getNameen() {
        return nameen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.NameEn
     *
     * @param nameen the value for t_basic_system_registry.NameEn
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setNameen(String nameen) {
        this.nameen = nameen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.Domain
     *
     * @return the value of t_basic_system_registry.Domain
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.Domain
     *
     * @param domain the value for t_basic_system_registry.Domain
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.ContextPath
     *
     * @return the value of t_basic_system_registry.ContextPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getContextpath() {
        return contextpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.ContextPath
     *
     * @param contextpath the value for t_basic_system_registry.ContextPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setContextpath(String contextpath) {
        this.contextpath = contextpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.HomePage
     *
     * @return the value of t_basic_system_registry.HomePage
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.HomePage
     *
     * @param homepage the value for t_basic_system_registry.HomePage
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.Type
     *
     * @return the value of t_basic_system_registry.Type
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.Type
     *
     * @param type the value for t_basic_system_registry.Type
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.LogoPath
     *
     * @return the value of t_basic_system_registry.LogoPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public String getLogopath() {
        return logopath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.LogoPath
     *
     * @param logopath the value for t_basic_system_registry.LogoPath
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setLogopath(String logopath) {
        this.logopath = logopath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_basic_system_registry.Status
     *
     * @return the value of t_basic_system_registry.Status
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_basic_system_registry.Status
     *
     * @param status the value for t_basic_system_registry.Status
     *
     * @ibatorgenerated Tue Nov 22 13:44:15 GMT+08:00 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}