package com.qi.assistant.web.model.model;

import com.qi.common.dao.model.BaseModel;

import java.math.BigDecimal;

public class ElectricDetails extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.Guid
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.ElectricGuid
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Long electricguid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.Grade
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Integer grade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.PeakRate
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Integer peakrate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.PeakQuantity
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Integer peakquantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.PeakPrice
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private BigDecimal peakprice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.PeakAmount
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private BigDecimal peakamount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.FlatRate
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Integer flatrate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.FlatQuantity
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private Integer flatquantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.FlatPrice
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private BigDecimal flatprice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_electric_details.FlatAmount
     *
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    private BigDecimal flatamount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.Guid
     *
     * @return the value of t_family_electric_details.Guid
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.Guid
     *
     * @param guid the value for t_family_electric_details.Guid
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.ElectricGuid
     *
     * @return the value of t_family_electric_details.ElectricGuid
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Long getElectricguid() {
        return electricguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.ElectricGuid
     *
     * @param electricguid the value for t_family_electric_details.ElectricGuid
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setElectricguid(Long electricguid) {
        this.electricguid = electricguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.Grade
     *
     * @return the value of t_family_electric_details.Grade
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.Grade
     *
     * @param grade the value for t_family_electric_details.Grade
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.PeakRate
     *
     * @return the value of t_family_electric_details.PeakRate
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Integer getPeakrate() {
        return peakrate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.PeakRate
     *
     * @param peakrate the value for t_family_electric_details.PeakRate
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setPeakrate(Integer peakrate) {
        this.peakrate = peakrate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.PeakQuantity
     *
     * @return the value of t_family_electric_details.PeakQuantity
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Integer getPeakquantity() {
        return peakquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.PeakQuantity
     *
     * @param peakquantity the value for t_family_electric_details.PeakQuantity
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setPeakquantity(Integer peakquantity) {
        this.peakquantity = peakquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.PeakPrice
     *
     * @return the value of t_family_electric_details.PeakPrice
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public BigDecimal getPeakprice() {
        return peakprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.PeakPrice
     *
     * @param peakprice the value for t_family_electric_details.PeakPrice
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setPeakprice(BigDecimal peakprice) {
        this.peakprice = peakprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.PeakAmount
     *
     * @return the value of t_family_electric_details.PeakAmount
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public BigDecimal getPeakamount() {
        return peakamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.PeakAmount
     *
     * @param peakamount the value for t_family_electric_details.PeakAmount
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setPeakamount(BigDecimal peakamount) {
        this.peakamount = peakamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.FlatRate
     *
     * @return the value of t_family_electric_details.FlatRate
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Integer getFlatrate() {
        return flatrate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.FlatRate
     *
     * @param flatrate the value for t_family_electric_details.FlatRate
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setFlatrate(Integer flatrate) {
        this.flatrate = flatrate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.FlatQuantity
     *
     * @return the value of t_family_electric_details.FlatQuantity
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public Integer getFlatquantity() {
        return flatquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.FlatQuantity
     *
     * @param flatquantity the value for t_family_electric_details.FlatQuantity
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setFlatquantity(Integer flatquantity) {
        this.flatquantity = flatquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.FlatPrice
     *
     * @return the value of t_family_electric_details.FlatPrice
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public BigDecimal getFlatprice() {
        return flatprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.FlatPrice
     *
     * @param flatprice the value for t_family_electric_details.FlatPrice
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setFlatprice(BigDecimal flatprice) {
        this.flatprice = flatprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_electric_details.FlatAmount
     *
     * @return the value of t_family_electric_details.FlatAmount
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public BigDecimal getFlatamount() {
        return flatamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_electric_details.FlatAmount
     *
     * @param flatamount the value for t_family_electric_details.FlatAmount
     * @ibatorgenerated Thu Aug 11 12:15:34 GMT+08:00 2016
     */
    public void setFlatamount(BigDecimal flatamount) {
        this.flatamount = flatamount;
    }
}