package com.qi.assistant.web.model.model;

import com.qi.common.dao.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

public class Gas extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.Guid
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.BeforeID
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private Long beforeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.BatchNumber
     *
     * @ibatorgenerated Fri Aug 05 09:54:05 GMT+08:00 2016
     */
    private String batchnumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.BillDate
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private String billdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.CurrentDate
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private Date currentdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.NextDate
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private Date nextdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.Employe
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private String employe;


    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.Quantity
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private Integer quantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.BeforeBalance
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private BigDecimal beforebalance;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.CurrentBalance
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private BigDecimal currentbalance;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.Total
     *
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    private BigDecimal total;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.IsValid
     *
     * @ibatorgenerated Thu Aug 04 15:33:07 GMT+08:00 2016
     */
    private Boolean isvalid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas.IsReset
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private Boolean isreset;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.Guid
     *
     * @return the value of t_family_gas.Guid
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.Guid
     *
     * @param guid the value for t_family_gas.Guid
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.BeforeID
     *
     * @return the value of t_family_gas.BeforeID
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public Long getBeforeid() {
        return beforeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.BeforeID
     *
     * @param beforeid the value for t_family_gas.BeforeID
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setBeforeid(Long beforeid) {
        this.beforeid = beforeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.BatchNumber
     *
     * @return the value of t_family_gas.BatchNumber
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public String getBatchnumber() {
        return batchnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.BatchNumber
     *
     * @param batchnumber the value for t_family_gas.BatchNumber
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setBatchnumber(String batchnumber) {
        this.batchnumber = batchnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.BillDate
     *
     * @return the value of t_family_gas.BillDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public String getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.BillDate
     *
     * @param billdate the value for t_family_gas.BillDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setBilldate(String billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.CurrentDate
     *
     * @return the value of t_family_gas.CurrentDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public Date getCurrentdate() {
        return currentdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.CurrentDate
     *
     * @param currentdate the value for t_family_gas.CurrentDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setCurrentdate(Date currentdate) {
        this.currentdate = currentdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.NextDate
     *
     * @return the value of t_family_gas.NextDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public Date getNextdate() {
        return nextdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.NextDate
     *
     * @param nextdate the value for t_family_gas.NextDate
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setNextdate(Date nextdate) {
        this.nextdate = nextdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.Employe
     *
     * @return the value of t_family_gas.Employe
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public String getEmploye() {
        return employe;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.Employe
     *
     * @param employe the value for t_family_gas.Employe
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setEmploye(String employe) {
        this.employe = employe;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.Quantity
     *
     * @return the value of t_family_gas.Quantity
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.Quantity
     *
     * @param quantity the value for t_family_gas.Quantity
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.BeforeBalance
     *
     * @return the value of t_family_gas.BeforeBalance
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public BigDecimal getBeforebalance() {
        return beforebalance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.BeforeBalance
     *
     * @param beforebalance the value for t_family_gas.BeforeBalance
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setBeforebalance(BigDecimal beforebalance) {
        this.beforebalance = beforebalance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.CurrentBalance
     *
     * @return the value of t_family_gas.CurrentBalance
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public BigDecimal getCurrentbalance() {
        return currentbalance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.CurrentBalance
     *
     * @param currentbalance the value for t_family_gas.CurrentBalance
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setCurrentbalance(BigDecimal currentbalance) {
        this.currentbalance = currentbalance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.Total
     *
     * @return the value of t_family_gas.Total
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.Total
     *
     * @param total the value for t_family_gas.Total
     * @ibatorgenerated Thu Jul 28 16:36:48 GMT+08:00 2016
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.IsValid
     *
     * @return the value of t_family_gas.IsValid
     * @ibatorgenerated Thu Aug 04 15:33:07 GMT+08:00 2016
     */
    public Boolean getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.IsValid
     *
     * @param isvalid the value for t_family_gas.IsValid
     * @ibatorgenerated Thu Aug 04 15:33:07 GMT+08:00 2016
     */
    public void setIsvalid(Boolean isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas.IsReset
     *
     * @return the value of t_family_gas.IsReset
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public Boolean getIsreset() {
        return isreset;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas.IsReset
     *
     * @param isreset the value for t_family_gas.IsReset
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setIsreset(Boolean isreset) {
        this.isreset = isreset;
    }
}