package com.qi.assistant.web.model.model;

import com.qi.common.dao.model.BaseModel;

import java.math.BigDecimal;

public class GasDetails extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.Guid
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.GasGuid
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private Long gasguid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.Grade
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private Integer grade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.GasQuantity
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private Integer gasquantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.GasPrice
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private BigDecimal gasprice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_gas_details.GasAmount
     *
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    private BigDecimal gasamount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.Guid
     *
     * @return the value of t_family_gas_details.Guid
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.Guid
     *
     * @param guid the value for t_family_gas_details.Guid
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.GasGuid
     *
     * @return the value of t_family_gas_details.GasGuid
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public Long getGasguid() {
        return gasguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.GasGuid
     *
     * @param gasguid the value for t_family_gas_details.GasGuid
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGasguid(Long gasguid) {
        this.gasguid = gasguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.Grade
     *
     * @return the value of t_family_gas_details.Grade
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.Grade
     *
     * @param grade the value for t_family_gas_details.Grade
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.GasQuantity
     *
     * @return the value of t_family_gas_details.GasQuantity
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public Integer getGasquantity() {
        return gasquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.GasQuantity
     *
     * @param gasquantity the value for t_family_gas_details.GasQuantity
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGasquantity(Integer gasquantity) {
        this.gasquantity = gasquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.GasPrice
     *
     * @return the value of t_family_gas_details.GasPrice
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public BigDecimal getGasprice() {
        return gasprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.GasPrice
     *
     * @param gasprice the value for t_family_gas_details.GasPrice
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGasprice(BigDecimal gasprice) {
        this.gasprice = gasprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_gas_details.GasAmount
     *
     * @return the value of t_family_gas_details.GasAmount
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public BigDecimal getGasamount() {
        return gasamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_gas_details.GasAmount
     *
     * @param gasamount the value for t_family_gas_details.GasAmount
     * @ibatorgenerated Fri Aug 05 10:00:11 GMT+08:00 2016
     */
    public void setGasamount(BigDecimal gasamount) {
        this.gasamount = gasamount;
    }
}