package com.qi.assistant.web.model.model;

import com.qi.common.dao.model.BaseModel;

import java.math.BigDecimal;

public class Options extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Guid
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.OptionsType
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private String optionstype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.IntervalType
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer intervaltype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.IntervalDate
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer intervaldate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Employe
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private String employe;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Grade
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer grade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Quantity
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer quantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Amend
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer amend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.PriceOne
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private BigDecimal priceone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.PriceTwo
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private BigDecimal pricetwo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_options.Formula
     *
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    private Integer formula;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Guid
     *
     * @return the value of t_family_options.Guid
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Guid
     *
     * @param guid the value for t_family_options.Guid
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.OptionsType
     *
     * @return the value of t_family_options.OptionsType
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public String getOptionstype() {
        return optionstype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.OptionsType
     *
     * @param optionstype the value for t_family_options.OptionsType
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setOptionstype(String optionstype) {
        this.optionstype = optionstype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.IntervalType
     *
     * @return the value of t_family_options.IntervalType
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getIntervaltype() {
        return intervaltype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.IntervalType
     *
     * @param intervaltype the value for t_family_options.IntervalType
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setIntervaltype(Integer intervaltype) {
        this.intervaltype = intervaltype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.IntervalDate
     *
     * @return the value of t_family_options.IntervalDate
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getIntervaldate() {
        return intervaldate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.IntervalDate
     *
     * @param intervaldate the value for t_family_options.IntervalDate
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setIntervaldate(Integer intervaldate) {
        this.intervaldate = intervaldate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Employe
     *
     * @return the value of t_family_options.Employe
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public String getEmploye() {
        return employe;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Employe
     *
     * @param employe the value for t_family_options.Employe
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setEmploye(String employe) {
        this.employe = employe;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Grade
     *
     * @return the value of t_family_options.Grade
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Grade
     *
     * @param grade the value for t_family_options.Grade
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Quantity
     *
     * @return the value of t_family_options.Quantity
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Quantity
     *
     * @param quantity the value for t_family_options.Quantity
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Amend
     *
     * @return the value of t_family_options.Amend
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getAmend() {
        return amend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Amend
     *
     * @param amend the value for t_family_options.Amend
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setAmend(Integer amend) {
        this.amend = amend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.PriceOne
     *
     * @return the value of t_family_options.PriceOne
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public BigDecimal getPriceone() {
        return priceone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.PriceOne
     *
     * @param priceone the value for t_family_options.PriceOne
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setPriceone(BigDecimal priceone) {
        this.priceone = priceone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.PriceTwo
     *
     * @return the value of t_family_options.PriceTwo
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public BigDecimal getPricetwo() {
        return pricetwo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.PriceTwo
     *
     * @param pricetwo the value for t_family_options.PriceTwo
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setPricetwo(BigDecimal pricetwo) {
        this.pricetwo = pricetwo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_options.Formula
     *
     * @return the value of t_family_options.Formula
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public Integer getFormula() {
        return formula;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_options.Formula
     *
     * @param formula the value for t_family_options.Formula
     * @ibatorgenerated Wed Jul 27 11:18:56 GMT+08:00 2016
     */
    public void setFormula(Integer formula) {
        this.formula = formula;
    }
}