package com.qi.assistant.web.model.model;

import com.qi.common.dao.model.BaseModel;

import java.math.BigDecimal;

public class WaterDetails extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.Guid
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private Long guid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.WaterGuid
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private Long waterguid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.Grade
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private Integer grade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.WaterQuantity
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private Integer waterquantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.WaterPrice
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private BigDecimal waterprice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.WaterAmount
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private BigDecimal wateramount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.DrainagePrice
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private BigDecimal drainageprice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.DrainageFormula
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private String drainageformula;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_family_water_details.DrainageAmount
     *
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    private BigDecimal drainageamount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.Guid
     *
     * @return the value of t_family_water_details.Guid
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.Guid
     *
     * @param guid the value for t_family_water_details.Guid
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.WaterGuid
     *
     * @return the value of t_family_water_details.WaterGuid
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public Long getWaterguid() {
        return waterguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.WaterGuid
     *
     * @param waterguid the value for t_family_water_details.WaterGuid
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setWaterguid(Long waterguid) {
        this.waterguid = waterguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.Grade
     *
     * @return the value of t_family_water_details.Grade
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.Grade
     *
     * @param grade the value for t_family_water_details.Grade
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.WaterQuantity
     *
     * @return the value of t_family_water_details.WaterQuantity
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public Integer getWaterquantity() {
        return waterquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.WaterQuantity
     *
     * @param waterquantity the value for t_family_water_details.WaterQuantity
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setWaterquantity(Integer waterquantity) {
        this.waterquantity = waterquantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.WaterPrice
     *
     * @return the value of t_family_water_details.WaterPrice
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public BigDecimal getWaterprice() {
        return waterprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.WaterPrice
     *
     * @param waterprice the value for t_family_water_details.WaterPrice
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setWaterprice(BigDecimal waterprice) {
        this.waterprice = waterprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.WaterAmount
     *
     * @return the value of t_family_water_details.WaterAmount
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public BigDecimal getWateramount() {
        return wateramount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.WaterAmount
     *
     * @param wateramount the value for t_family_water_details.WaterAmount
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setWateramount(BigDecimal wateramount) {
        this.wateramount = wateramount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.DrainagePrice
     *
     * @return the value of t_family_water_details.DrainagePrice
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public BigDecimal getDrainageprice() {
        return drainageprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.DrainagePrice
     *
     * @param drainageprice the value for t_family_water_details.DrainagePrice
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setDrainageprice(BigDecimal drainageprice) {
        this.drainageprice = drainageprice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.DrainageFormula
     *
     * @return the value of t_family_water_details.DrainageFormula
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public String getDrainageformula() {
        return drainageformula;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.DrainageFormula
     *
     * @param drainageformula the value for t_family_water_details.DrainageFormula
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setDrainageformula(String drainageformula) {
        this.drainageformula = drainageformula;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_family_water_details.DrainageAmount
     *
     * @return the value of t_family_water_details.DrainageAmount
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public BigDecimal getDrainageamount() {
        return drainageamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_family_water_details.DrainageAmount
     *
     * @param drainageamount the value for t_family_water_details.DrainageAmount
     * @ibatorgenerated Tue Aug 30 15:25:34 GMT+08:00 2016
     */
    public void setDrainageamount(BigDecimal drainageamount) {
        this.drainageamount = drainageamount;
    }
}