package com.qi.assistant.web.model.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ElectricExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public ElectricExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    protected ElectricExample(ElectricExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_family_electric
     *
     * @ibatorgenerated Thu Aug 11 11:48:11 GMT+08:00 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return this;
        }

        public Criteria andGuidEqualTo(Long value) {
            addCriterion("Guid =", value, "guid");
            return this;
        }

        public Criteria andGuidNotEqualTo(Long value) {
            addCriterion("Guid <>", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThan(Long value) {
            addCriterion("Guid >", value, "guid");
            return this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(Long value) {
            addCriterion("Guid >=", value, "guid");
            return this;
        }

        public Criteria andGuidLessThan(Long value) {
            addCriterion("Guid <", value, "guid");
            return this;
        }

        public Criteria andGuidLessThanOrEqualTo(Long value) {
            addCriterion("Guid <=", value, "guid");
            return this;
        }

        public Criteria andGuidIn(List values) {
            addCriterion("Guid in", values, "guid");
            return this;
        }

        public Criteria andGuidNotIn(List values) {
            addCriterion("Guid not in", values, "guid");
            return this;
        }

        public Criteria andGuidBetween(Long value1, Long value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return this;
        }

        public Criteria andGuidNotBetween(Long value1, Long value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return this;
        }

        public Criteria andBeforeidIsNull() {
            addCriterion("BeforeID is null");
            return this;
        }

        public Criteria andBeforeidIsNotNull() {
            addCriterion("BeforeID is not null");
            return this;
        }

        public Criteria andBeforeidEqualTo(Long value) {
            addCriterion("BeforeID =", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidNotEqualTo(Long value) {
            addCriterion("BeforeID <>", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidGreaterThan(Long value) {
            addCriterion("BeforeID >", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidGreaterThanOrEqualTo(Long value) {
            addCriterion("BeforeID >=", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidLessThan(Long value) {
            addCriterion("BeforeID <", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidLessThanOrEqualTo(Long value) {
            addCriterion("BeforeID <=", value, "beforeid");
            return this;
        }

        public Criteria andBeforeidIn(List values) {
            addCriterion("BeforeID in", values, "beforeid");
            return this;
        }

        public Criteria andBeforeidNotIn(List values) {
            addCriterion("BeforeID not in", values, "beforeid");
            return this;
        }

        public Criteria andBeforeidBetween(Long value1, Long value2) {
            addCriterion("BeforeID between", value1, value2, "beforeid");
            return this;
        }

        public Criteria andBeforeidNotBetween(Long value1, Long value2) {
            addCriterion("BeforeID not between", value1, value2, "beforeid");
            return this;
        }

        public Criteria andBatchnumberIsNull() {
            addCriterion("BatchNumber is null");
            return this;
        }

        public Criteria andBatchnumberIsNotNull() {
            addCriterion("BatchNumber is not null");
            return this;
        }

        public Criteria andBatchnumberEqualTo(String value) {
            addCriterion("BatchNumber =", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberNotEqualTo(String value) {
            addCriterion("BatchNumber <>", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberGreaterThan(String value) {
            addCriterion("BatchNumber >", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberGreaterThanOrEqualTo(String value) {
            addCriterion("BatchNumber >=", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberLessThan(String value) {
            addCriterion("BatchNumber <", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberLessThanOrEqualTo(String value) {
            addCriterion("BatchNumber <=", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberLike(String value) {
            addCriterion("BatchNumber like", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberNotLike(String value) {
            addCriterion("BatchNumber not like", value, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberIn(List values) {
            addCriterion("BatchNumber in", values, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberNotIn(List values) {
            addCriterion("BatchNumber not in", values, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberBetween(String value1, String value2) {
            addCriterion("BatchNumber between", value1, value2, "batchnumber");
            return this;
        }

        public Criteria andBatchnumberNotBetween(String value1, String value2) {
            addCriterion("BatchNumber not between", value1, value2, "batchnumber");
            return this;
        }

        public Criteria andBilldateIsNull() {
            addCriterion("BillDate is null");
            return this;
        }

        public Criteria andBilldateIsNotNull() {
            addCriterion("BillDate is not null");
            return this;
        }

        public Criteria andBilldateEqualTo(String value) {
            addCriterion("BillDate =", value, "billdate");
            return this;
        }

        public Criteria andBilldateNotEqualTo(String value) {
            addCriterion("BillDate <>", value, "billdate");
            return this;
        }

        public Criteria andBilldateGreaterThan(String value) {
            addCriterion("BillDate >", value, "billdate");
            return this;
        }

        public Criteria andBilldateGreaterThanOrEqualTo(String value) {
            addCriterion("BillDate >=", value, "billdate");
            return this;
        }

        public Criteria andBilldateLessThan(String value) {
            addCriterion("BillDate <", value, "billdate");
            return this;
        }

        public Criteria andBilldateLessThanOrEqualTo(String value) {
            addCriterion("BillDate <=", value, "billdate");
            return this;
        }

        public Criteria andBilldateLike(String value) {
            addCriterion("BillDate like", value, "billdate");
            return this;
        }

        public Criteria andBilldateNotLike(String value) {
            addCriterion("BillDate not like", value, "billdate");
            return this;
        }

        public Criteria andBilldateIn(List values) {
            addCriterion("BillDate in", values, "billdate");
            return this;
        }

        public Criteria andBilldateNotIn(List values) {
            addCriterion("BillDate not in", values, "billdate");
            return this;
        }

        public Criteria andBilldateBetween(String value1, String value2) {
            addCriterion("BillDate between", value1, value2, "billdate");
            return this;
        }

        public Criteria andBilldateNotBetween(String value1, String value2) {
            addCriterion("BillDate not between", value1, value2, "billdate");
            return this;
        }

        public Criteria andCurrentdateIsNull() {
            addCriterion("CurrentDate is null");
            return this;
        }

        public Criteria andCurrentdateIsNotNull() {
            addCriterion("CurrentDate is not null");
            return this;
        }

        public Criteria andCurrentdateEqualTo(Date value) {
            addCriterionForJDBCDate("CurrentDate =", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CurrentDate <>", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateGreaterThan(Date value) {
            addCriterionForJDBCDate("CurrentDate >", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CurrentDate >=", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateLessThan(Date value) {
            addCriterionForJDBCDate("CurrentDate <", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CurrentDate <=", value, "currentdate");
            return this;
        }

        public Criteria andCurrentdateIn(List values) {
            addCriterionForJDBCDate("CurrentDate in", values, "currentdate");
            return this;
        }

        public Criteria andCurrentdateNotIn(List values) {
            addCriterionForJDBCDate("CurrentDate not in", values, "currentdate");
            return this;
        }

        public Criteria andCurrentdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CurrentDate between", value1, value2, "currentdate");
            return this;
        }

        public Criteria andCurrentdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CurrentDate not between", value1, value2, "currentdate");
            return this;
        }

        public Criteria andNextdateIsNull() {
            addCriterion("NextDate is null");
            return this;
        }

        public Criteria andNextdateIsNotNull() {
            addCriterion("NextDate is not null");
            return this;
        }

        public Criteria andNextdateEqualTo(Date value) {
            addCriterionForJDBCDate("NextDate =", value, "nextdate");
            return this;
        }

        public Criteria andNextdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("NextDate <>", value, "nextdate");
            return this;
        }

        public Criteria andNextdateGreaterThan(Date value) {
            addCriterionForJDBCDate("NextDate >", value, "nextdate");
            return this;
        }

        public Criteria andNextdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NextDate >=", value, "nextdate");
            return this;
        }

        public Criteria andNextdateLessThan(Date value) {
            addCriterionForJDBCDate("NextDate <", value, "nextdate");
            return this;
        }

        public Criteria andNextdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NextDate <=", value, "nextdate");
            return this;
        }

        public Criteria andNextdateIn(List values) {
            addCriterionForJDBCDate("NextDate in", values, "nextdate");
            return this;
        }

        public Criteria andNextdateNotIn(List values) {
            addCriterionForJDBCDate("NextDate not in", values, "nextdate");
            return this;
        }

        public Criteria andNextdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NextDate between", value1, value2, "nextdate");
            return this;
        }

        public Criteria andNextdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NextDate not between", value1, value2, "nextdate");
            return this;
        }

        public Criteria andEmployeIsNull() {
            addCriterion("Employe is null");
            return this;
        }

        public Criteria andEmployeIsNotNull() {
            addCriterion("Employe is not null");
            return this;
        }

        public Criteria andEmployeEqualTo(String value) {
            addCriterion("Employe =", value, "employe");
            return this;
        }

        public Criteria andEmployeNotEqualTo(String value) {
            addCriterion("Employe <>", value, "employe");
            return this;
        }

        public Criteria andEmployeGreaterThan(String value) {
            addCriterion("Employe >", value, "employe");
            return this;
        }

        public Criteria andEmployeGreaterThanOrEqualTo(String value) {
            addCriterion("Employe >=", value, "employe");
            return this;
        }

        public Criteria andEmployeLessThan(String value) {
            addCriterion("Employe <", value, "employe");
            return this;
        }

        public Criteria andEmployeLessThanOrEqualTo(String value) {
            addCriterion("Employe <=", value, "employe");
            return this;
        }

        public Criteria andEmployeLike(String value) {
            addCriterion("Employe like", value, "employe");
            return this;
        }

        public Criteria andEmployeNotLike(String value) {
            addCriterion("Employe not like", value, "employe");
            return this;
        }

        public Criteria andEmployeIn(List values) {
            addCriterion("Employe in", values, "employe");
            return this;
        }

        public Criteria andEmployeNotIn(List values) {
            addCriterion("Employe not in", values, "employe");
            return this;
        }

        public Criteria andEmployeBetween(String value1, String value2) {
            addCriterion("Employe between", value1, value2, "employe");
            return this;
        }

        public Criteria andEmployeNotBetween(String value1, String value2) {
            addCriterion("Employe not between", value1, value2, "employe");
            return this;
        }

        public Criteria andPeakquantityIsNull() {
            addCriterion("PeakQuantity is null");
            return this;
        }

        public Criteria andPeakquantityIsNotNull() {
            addCriterion("PeakQuantity is not null");
            return this;
        }

        public Criteria andPeakquantityEqualTo(Integer value) {
            addCriterion("PeakQuantity =", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityNotEqualTo(Integer value) {
            addCriterion("PeakQuantity <>", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityGreaterThan(Integer value) {
            addCriterion("PeakQuantity >", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("PeakQuantity >=", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityLessThan(Integer value) {
            addCriterion("PeakQuantity <", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityLessThanOrEqualTo(Integer value) {
            addCriterion("PeakQuantity <=", value, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityIn(List values) {
            addCriterion("PeakQuantity in", values, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityNotIn(List values) {
            addCriterion("PeakQuantity not in", values, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityBetween(Integer value1, Integer value2) {
            addCriterion("PeakQuantity between", value1, value2, "peakquantity");
            return this;
        }

        public Criteria andPeakquantityNotBetween(Integer value1, Integer value2) {
            addCriterion("PeakQuantity not between", value1, value2, "peakquantity");
            return this;
        }

        public Criteria andFlatquantityIsNull() {
            addCriterion("FlatQuantity is null");
            return this;
        }

        public Criteria andFlatquantityIsNotNull() {
            addCriterion("FlatQuantity is not null");
            return this;
        }

        public Criteria andFlatquantityEqualTo(Integer value) {
            addCriterion("FlatQuantity =", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityNotEqualTo(Integer value) {
            addCriterion("FlatQuantity <>", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityGreaterThan(Integer value) {
            addCriterion("FlatQuantity >", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("FlatQuantity >=", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityLessThan(Integer value) {
            addCriterion("FlatQuantity <", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityLessThanOrEqualTo(Integer value) {
            addCriterion("FlatQuantity <=", value, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityIn(List values) {
            addCriterion("FlatQuantity in", values, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityNotIn(List values) {
            addCriterion("FlatQuantity not in", values, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityBetween(Integer value1, Integer value2) {
            addCriterion("FlatQuantity between", value1, value2, "flatquantity");
            return this;
        }

        public Criteria andFlatquantityNotBetween(Integer value1, Integer value2) {
            addCriterion("FlatQuantity not between", value1, value2, "flatquantity");
            return this;
        }

        public Criteria andBeforebalanceIsNull() {
            addCriterion("BeforeBalance is null");
            return this;
        }

        public Criteria andBeforebalanceIsNotNull() {
            addCriterion("BeforeBalance is not null");
            return this;
        }

        public Criteria andBeforebalanceEqualTo(BigDecimal value) {
            addCriterion("BeforeBalance =", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceNotEqualTo(BigDecimal value) {
            addCriterion("BeforeBalance <>", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceGreaterThan(BigDecimal value) {
            addCriterion("BeforeBalance >", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BeforeBalance >=", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceLessThan(BigDecimal value) {
            addCriterion("BeforeBalance <", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BeforeBalance <=", value, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceIn(List values) {
            addCriterion("BeforeBalance in", values, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceNotIn(List values) {
            addCriterion("BeforeBalance not in", values, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BeforeBalance between", value1, value2, "beforebalance");
            return this;
        }

        public Criteria andBeforebalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BeforeBalance not between", value1, value2, "beforebalance");
            return this;
        }

        public Criteria andCurrentbalanceIsNull() {
            addCriterion("CurrentBalance is null");
            return this;
        }

        public Criteria andCurrentbalanceIsNotNull() {
            addCriterion("CurrentBalance is not null");
            return this;
        }

        public Criteria andCurrentbalanceEqualTo(BigDecimal value) {
            addCriterion("CurrentBalance =", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceNotEqualTo(BigDecimal value) {
            addCriterion("CurrentBalance <>", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceGreaterThan(BigDecimal value) {
            addCriterion("CurrentBalance >", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CurrentBalance >=", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceLessThan(BigDecimal value) {
            addCriterion("CurrentBalance <", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CurrentBalance <=", value, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceIn(List values) {
            addCriterion("CurrentBalance in", values, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceNotIn(List values) {
            addCriterion("CurrentBalance not in", values, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CurrentBalance between", value1, value2, "currentbalance");
            return this;
        }

        public Criteria andCurrentbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CurrentBalance not between", value1, value2, "currentbalance");
            return this;
        }

        public Criteria andDepositedIsNull() {
            addCriterion("Deposited is null");
            return this;
        }

        public Criteria andDepositedIsNotNull() {
            addCriterion("Deposited is not null");
            return this;
        }

        public Criteria andDepositedEqualTo(BigDecimal value) {
            addCriterion("Deposited =", value, "deposited");
            return this;
        }

        public Criteria andDepositedNotEqualTo(BigDecimal value) {
            addCriterion("Deposited <>", value, "deposited");
            return this;
        }

        public Criteria andDepositedGreaterThan(BigDecimal value) {
            addCriterion("Deposited >", value, "deposited");
            return this;
        }

        public Criteria andDepositedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Deposited >=", value, "deposited");
            return this;
        }

        public Criteria andDepositedLessThan(BigDecimal value) {
            addCriterion("Deposited <", value, "deposited");
            return this;
        }

        public Criteria andDepositedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Deposited <=", value, "deposited");
            return this;
        }

        public Criteria andDepositedIn(List values) {
            addCriterion("Deposited in", values, "deposited");
            return this;
        }

        public Criteria andDepositedNotIn(List values) {
            addCriterion("Deposited not in", values, "deposited");
            return this;
        }

        public Criteria andDepositedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Deposited between", value1, value2, "deposited");
            return this;
        }

        public Criteria andDepositedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Deposited not between", value1, value2, "deposited");
            return this;
        }

        public Criteria andAdditionalIsNull() {
            addCriterion("Additional is null");
            return this;
        }

        public Criteria andAdditionalIsNotNull() {
            addCriterion("Additional is not null");
            return this;
        }

        public Criteria andAdditionalEqualTo(BigDecimal value) {
            addCriterion("Additional =", value, "additional");
            return this;
        }

        public Criteria andAdditionalNotEqualTo(BigDecimal value) {
            addCriterion("Additional <>", value, "additional");
            return this;
        }

        public Criteria andAdditionalGreaterThan(BigDecimal value) {
            addCriterion("Additional >", value, "additional");
            return this;
        }

        public Criteria andAdditionalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Additional >=", value, "additional");
            return this;
        }

        public Criteria andAdditionalLessThan(BigDecimal value) {
            addCriterion("Additional <", value, "additional");
            return this;
        }

        public Criteria andAdditionalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Additional <=", value, "additional");
            return this;
        }

        public Criteria andAdditionalIn(List values) {
            addCriterion("Additional in", values, "additional");
            return this;
        }

        public Criteria andAdditionalNotIn(List values) {
            addCriterion("Additional not in", values, "additional");
            return this;
        }

        public Criteria andAdditionalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Additional between", value1, value2, "additional");
            return this;
        }

        public Criteria andAdditionalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Additional not between", value1, value2, "additional");
            return this;
        }

        public Criteria andTotalshouldIsNull() {
            addCriterion("TotalShould is null");
            return this;
        }

        public Criteria andTotalshouldIsNotNull() {
            addCriterion("TotalShould is not null");
            return this;
        }

        public Criteria andTotalshouldEqualTo(BigDecimal value) {
            addCriterion("TotalShould =", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldNotEqualTo(BigDecimal value) {
            addCriterion("TotalShould <>", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldGreaterThan(BigDecimal value) {
            addCriterion("TotalShould >", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalShould >=", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldLessThan(BigDecimal value) {
            addCriterion("TotalShould <", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalShould <=", value, "totalshould");
            return this;
        }

        public Criteria andTotalshouldIn(List values) {
            addCriterion("TotalShould in", values, "totalshould");
            return this;
        }

        public Criteria andTotalshouldNotIn(List values) {
            addCriterion("TotalShould not in", values, "totalshould");
            return this;
        }

        public Criteria andTotalshouldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalShould between", value1, value2, "totalshould");
            return this;
        }

        public Criteria andTotalshouldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalShould not between", value1, value2, "totalshould");
            return this;
        }

        public Criteria andTotalactualIsNull() {
            addCriterion("TotalActual is null");
            return this;
        }

        public Criteria andTotalactualIsNotNull() {
            addCriterion("TotalActual is not null");
            return this;
        }

        public Criteria andTotalactualEqualTo(BigDecimal value) {
            addCriterion("TotalActual =", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualNotEqualTo(BigDecimal value) {
            addCriterion("TotalActual <>", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualGreaterThan(BigDecimal value) {
            addCriterion("TotalActual >", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalActual >=", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualLessThan(BigDecimal value) {
            addCriterion("TotalActual <", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TotalActual <=", value, "totalactual");
            return this;
        }

        public Criteria andTotalactualIn(List values) {
            addCriterion("TotalActual in", values, "totalactual");
            return this;
        }

        public Criteria andTotalactualNotIn(List values) {
            addCriterion("TotalActual not in", values, "totalactual");
            return this;
        }

        public Criteria andTotalactualBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalActual between", value1, value2, "totalactual");
            return this;
        }

        public Criteria andTotalactualNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TotalActual not between", value1, value2, "totalactual");
            return this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("Creator is null");
            return this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("Creator is not null");
            return this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("Creator =", value, "creator");
            return this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("Creator <>", value, "creator");
            return this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("Creator >", value, "creator");
            return this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("Creator >=", value, "creator");
            return this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("Creator <", value, "creator");
            return this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("Creator <=", value, "creator");
            return this;
        }

        public Criteria andCreatorIn(List values) {
            addCriterion("Creator in", values, "creator");
            return this;
        }

        public Criteria andCreatorNotIn(List values) {
            addCriterion("Creator not in", values, "creator");
            return this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("Creator between", value1, value2, "creator");
            return this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("Creator not between", value1, value2, "creator");
            return this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeIn(List values) {
            addCriterion("CreateTime in", values, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotIn(List values) {
            addCriterion("CreateTime not in", values, "createtime");
            return this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("Updater is null");
            return this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("Updater is not null");
            return this;
        }

        public Criteria andUpdaterEqualTo(Long value) {
            addCriterion("Updater =", value, "updater");
            return this;
        }

        public Criteria andUpdaterNotEqualTo(Long value) {
            addCriterion("Updater <>", value, "updater");
            return this;
        }

        public Criteria andUpdaterGreaterThan(Long value) {
            addCriterion("Updater >", value, "updater");
            return this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(Long value) {
            addCriterion("Updater >=", value, "updater");
            return this;
        }

        public Criteria andUpdaterLessThan(Long value) {
            addCriterion("Updater <", value, "updater");
            return this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(Long value) {
            addCriterion("Updater <=", value, "updater");
            return this;
        }

        public Criteria andUpdaterIn(List values) {
            addCriterion("Updater in", values, "updater");
            return this;
        }

        public Criteria andUpdaterNotIn(List values) {
            addCriterion("Updater not in", values, "updater");
            return this;
        }

        public Criteria andUpdaterBetween(Long value1, Long value2) {
            addCriterion("Updater between", value1, value2, "updater");
            return this;
        }

        public Criteria andUpdaterNotBetween(Long value1, Long value2) {
            addCriterion("Updater not between", value1, value2, "updater");
            return this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeIn(List values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotIn(List values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("IsValid is null");
            return this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("IsValid is not null");
            return this;
        }

        public Criteria andIsvalidEqualTo(Boolean value) {
            addCriterion("IsValid =", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidNotEqualTo(Boolean value) {
            addCriterion("IsValid <>", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidGreaterThan(Boolean value) {
            addCriterion("IsValid >", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsValid >=", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidLessThan(Boolean value) {
            addCriterion("IsValid <", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(Boolean value) {
            addCriterion("IsValid <=", value, "isvalid");
            return this;
        }

        public Criteria andIsvalidIn(List values) {
            addCriterion("IsValid in", values, "isvalid");
            return this;
        }

        public Criteria andIsvalidNotIn(List values) {
            addCriterion("IsValid not in", values, "isvalid");
            return this;
        }

        public Criteria andIsvalidBetween(Boolean value1, Boolean value2) {
            addCriterion("IsValid between", value1, value2, "isvalid");
            return this;
        }

        public Criteria andIsvalidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsValid not between", value1, value2, "isvalid");
            return this;
        }

        public Criteria andIsresetIsNull() {
            addCriterion("IsReset is null");
            return this;
        }

        public Criteria andIsresetIsNotNull() {
            addCriterion("IsReset is not null");
            return this;
        }

        public Criteria andIsresetEqualTo(Boolean value) {
            addCriterion("IsReset =", value, "isreset");
            return this;
        }

        public Criteria andIsresetNotEqualTo(Boolean value) {
            addCriterion("IsReset <>", value, "isreset");
            return this;
        }

        public Criteria andIsresetGreaterThan(Boolean value) {
            addCriterion("IsReset >", value, "isreset");
            return this;
        }

        public Criteria andIsresetGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsReset >=", value, "isreset");
            return this;
        }

        public Criteria andIsresetLessThan(Boolean value) {
            addCriterion("IsReset <", value, "isreset");
            return this;
        }

        public Criteria andIsresetLessThanOrEqualTo(Boolean value) {
            addCriterion("IsReset <=", value, "isreset");
            return this;
        }

        public Criteria andIsresetIn(List values) {
            addCriterion("IsReset in", values, "isreset");
            return this;
        }

        public Criteria andIsresetNotIn(List values) {
            addCriterion("IsReset not in", values, "isreset");
            return this;
        }

        public Criteria andIsresetBetween(Boolean value1, Boolean value2) {
            addCriterion("IsReset between", value1, value2, "isreset");
            return this;
        }

        public Criteria andIsresetNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsReset not between", value1, value2, "isreset");
            return this;
        }
    }
}